---
title: "Literature review"
author: "Jonathan Che"
date: "3/2/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

There is a pretty massive literature on power analyses for multilevel models, out of the 90s-00s.
These papers are all focused on the overall means and variances.

The general model used in these papers is:

$$
\begin{align}
  Y_{ij} &= \beta_{0j} + \beta_{1j} X_{ij} + r_{ij} \\
  \beta_{0j} &= \gamma_{00} + \gamma_{01}W_j + u_{0j} \\
  \beta_{1j} &= \gamma_{10} + \gamma_{11}W_j + u_{1j}
\end{align}
$$
for some individual-level covariates $X_{ij}$ and site-level covariates $W_j$.
This gives us:
$$
Y_{ij} = \gamma_{00} + \gamma_{01}W_j + u_{0j} + \gamma_{10} X_{ij} + \gamma_{11}W_j X_{ij} + u_{1j} X_{ij} + r_{ij}
$$

The goals are to estimate the following:

 * Fixed effects: overall mean $\gamma_{00}$; fixed intercept effect $\gamma_{10}$; covariate effect $\gamma_{10}$; cross-level interaction $\gamma_{11}$
 * Variance components: variances of $u_{0j}$, $u_{1j}$, and $r_{ij}$

A normal distribution is typically placed on the $u$s, so it makes sense to just estimate the means of the $\beta$s and the variances of the $u$s.

## Our setting

We're actually interested in estimating the random effects $u_{1j}$s from the equation above!
This is straightforward in the normal-normal model (we get the usual shrinkage estimates); it's presumably not closed-form for other models.

Question: once we've estimated the random effects, is it possible to do frequentist inference on them?
Answer: yes! See https://core.ac.uk/download/pdf/38903061.pdf for an explanation (and also comments on why frequentist inference is bad/hard/an area of research); inference is just standard normal-model stuff.

Follow-up question: have people tried frequentist inference on the random effects, to see if they cross zero?
Answer: haven't seen any papers doing this yet...



